#!/bin/sh
if [ "$PC" = "voidlinux" ]; then
    doas xbps-install -S >/dev/null 2>&1
    quantidade=$(xbps-install -un 2> /dev/null | wc -l)
elif [ "$PC" = "archlinux" ] || [ "$PC" = "manjaro" ]; then
    doas pacman -Sy >/dev/null 2>&1
    quantidade=$(pacman -Qu 2> /dev/null | wc -l)
elif [ "$PC" = "linuxmint" ]; then
    doas apt update >/dev/null 2>&1
    quantidade=$(apt list --upgradable 2> /dev/null | wc -l)
fi

if [ "$quantidade" -gt 30 ]; then
    notify-send -u critical "Atualize os pacotes!" "$quantidade pacotes esperando atualização"
fi
