#!/bin/sh

# Autenticação utilizada
# Exemplo: sudo -A ou doas --
auth="doas_askpass"
dmenu="dmenu -a -l 35 -h 20 -c -cw 300"

#config
mount_dir="/tmp"

# desmontar
desmontar() {
    select=$(grep "/mnt\|$mount_dir/" /proc/self/mounts \
        | cut -d " " -f2 \
        | sort \
        | $dmenu -p "desmontar" \
    )

    [ -n "$select" ] \
        && $auth umount "$select" \
        && notify-send \
            "desmontar" \
            "$select desmontado" \
        && rm -d "$select"
}

# montar usb
montar_usb() {
    select="$(lsblk -rpo "name,type,size,mountpoint" \
        | awk '{ if ($2=="part"&&$4=="" || $2=="rom"&&$4=="" || $3=="1,4M"&&$4=="") printf "%s (%s)\n",$1,$3}' \
        | $dmenu -p "禍 montar usb" \
        | cut -d " " -f1)"

    [ -z "$select" ] \
        && exit 0

    mount_point="$HOME/mnt/usb"
    partition_type="$(lsblk -no "fstype" "$select")"

    [ ! -d "$mount_point" ] \
        && mkdir "$mount_point" \
        && case "$partition_type" in
            vfat)
                $auth mount -t "$partition_type" "$select" "$mount_point" -o rw,umask=0000 \
                ;;
            exfat)
                $auth mount "$select" "$mount_point" -o rw,umask=0000 \
                ;;
            *)
                $auth mount "$select" "$mount_point"
                user="$(whoami)"
                user_group="$(groups | cut -d " " -f1)"
                $auth chown "$user":"$user_group" 741 "$mount_point"
                ;;
            esac \
        && notify-send \
            "禍 montar usb $partition_type" \
            "$select montado em $mount_point"
}

# montar iso
montar_iso() {
    search="$HOME/Downloads"
    select=$(find "$search" -type f \
            -iname "*.iso" -o \
            -iname "*.img" -o \
            -iname "*.bin" -o \
            -iname "*.mdf" -o \
            -iname "*.nrg" \
        | cut -d / -f 5 \
        | $dmenu -p "﫭 montar iso" \
    )

    [ -z "$select" ] \
        && exit 0

    mount_point="$HOME/mnt/iso"
    set -x

    [ ! -d "$mount_point" ] \
        && mkdir "$mount_point"
    $auth mount -o loop "$search/$select" "$mount_point" \
    && notify-send \
    "﫭 montar iso" \
    "$select montado em $mount_point"
}

# montar android
montar_android() {
    select=$(simple-mtpfs -l 2>/dev/null \
        | $dmenu -p " montar android" \
        | cut -d ":" -f1 \
    )

    [ -z "$select" ] \
        && exit 0

    mount_point="$HOME/mnt/android"

    [ ! -d "$mount_point" ] \
        && mkdir "$mount_point" \
        && simple-mtpfs --device "$select" "$mount_point" \
        && notify-send \
            " montar android" \
            "$select montado em $mount_point"
}

# menu
case $(printf "%s\n" \
    "desmontar" \
    "禍 montar usb" \
    "﫭 montar iso" \
    " montar android" \
    | $dmenu \
    ) in
    "desmontar")
        desmontar
        ;;
    "禍 montar usb")
        montar_usb
        ;;
    "﫭 montar iso")
        montar_iso
        ;;
    " montar android")
        montar_android
        ;;
esac
