#!/usr/bin/env bash

main() {
  bssid=$(nmcli device wifi list | sed -n '1!p' | cut -b 9- | dmenu -a -h 20 -l 10 -c -cw 500 -p "Selecione Wifi  :" | cut -d' ' -f1)
  pass=$(echo "" | dmenu -a -c -cw 600 -p "Digite uma senha  :")
  [ -n "$pass" ] && nmcli device wifi connect "$bssid" password "$pass" || nmcli device wifi connect "$bssid"
  sleep 10
  if ping -q -c 2 -W 2 google.com >/dev/null; then
    notify-send "A sua internet esta funcionando :)"
  else
    notify-send "A sua internet não esta funcionando :("
  fi
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
