#!/bin/sh
selecao=$(tac < "$HISTFILE" | cut -d ';' -f2 | dmenu -l 35 -h 20)
[ -n "$selecao" ] || exit
printf "%s" "$selecao" | xclip -selection clipboard && \
                        notify-send Copiado "$selecao"
