#!/bin/sh

lista="$HOME/code/shell/listas/editar"
selecionado=$(cut -d';' -f1 "$lista" | dmenu -l 15 -g 3 -h 20 -c -cw 800 -p " Editar:")
[ -z "$selecionado" ] && exit 0 # Sai caso nada seja selecionado
arquivo=$(grep -m 1 "$selecionado" "$lista" | cut -d';' -f2)
extensao="${arquivo##*.}"

[ "$extensao" = "org" ] && VISUAL="emacsclient -n -c"
eval "$VISUAL" "$arquivo"
