#!/usr/bin/env sh
selecionado=$(cut -d ';' -f1 "$HOME/code/shellscripts/listas/emojis" | uniq -u | fzf | sed "s/ .*//")

# Sai caso nenhum é selecionado.
[ -z "$selecionado" ] && exit

echo -n "$selecionado" | xclip -selection clipboard && notify-send -i emoji "'$selecionado' copiado."
