#!/usr/bin/env sh

print_nome="print_$(date '+%d_%H:%M:%S').png"
visualizar=$(nsxiv "$HOME/$print_nome")

case "$(printf "uma area selecionada\\njanela atual\\ntela cheia (Temporizar)\\numa area selecionada (copiar)\\njanela atual (copiar)\\ntela cheia (Temporizar) (copiar)" | fzf)" in
    "uma area selecionada")
        maim -s "$print_nome" && $visualizar ;;
    "janela atual")
        maim -i "$(xdotool getactivewindow)" "$print_nome" && $visualizar ;;
    "tela cheia (Temporizar)")
        tempo=$(echo "" | fzf --prompt="Esperar em segundos: ")
        sleep "$tempo" && maim "$print_nome" && $visualizar ;;
    "uma area selecionada (copiar)")
        maim -s | xclip -selection clipboard -t image/png ;;
    "janela atual (copiar)")
        maim -i "$(xdotool getactivewindow)" | xclip -selection clipboard -t image/png ;;
    "tela cheia (Temporizar) (copiar)")
        tempo=$(echo "" | fzf --prompt="Esperar em segundos: ")
        sleep "$tempo" && maim | xclip -selection clipboard -t image/png ;;
esac
