#!/usr/bin/env sh

lista="$HOME/code/shell/listas/editar"
selecionado=$(cut -d';' -f1 "$lista" | fzf --prompt=" Editar:")
[ -z "$selecionado" ] && exit 0 # Sai caso nada seja selecionado
arquivo=$(grep -m 1 "$selecionado" "$lista" | cut -d';' -f2)
extensao="${arquivo##*.}"

[ "$extensao" = "org" ] && VISUAL="emacsclient -n -c"
eval "$VISUAL" "$arquivo"
