#!/usr/bin/env sh
if [ "$1" = "info" ]; then
    data=" $(date "+%a %d/%m/%Y - %H:%M")"
    musica=" 🎶 $(musica tocando)"
    volume=" $(volume)"
    programa=$(dmenu_path | fzf --header="$data$musica$volume")
    exec devour "$programa"
else
    programa=$(dmenu_path | fzf)
    exec devour "$programa"
fi
