#!/usr/bin/env sh

# atualiza listas
update() {
    man -k . > "$HOME/.cache/mans"
    cheat -l > "$HOME/.cache/cheats"
    awman-update
    exit
}

[ "$1" = "update" ] && update


case $(printf "manpages\ncheatsheets\nwikipages" | fzf --header "Procurar por?") in
    manpages)
        escolha=$(cat "$HOME/.cache/mans" | fzf)
        echo "$escolha" | cut -d' ' -f1 | sed "s/[^[:alpha:]]//g" | xargs man
        ;;
    cheatsheets)
        escolha=$(cat "$HOME/.cache/cheats" | fzf)
        echo "$escolha" | cut -d' ' -f1 | sed "s/[^[:alpha:]]//g" | xargs cheat
        ;;
    wikipages)
        printf "Procurar na archwiki? " >&2
        read -r pesquisado
        awman -k "$pesquisado"
        ;;
esac
