#!/usr/bin/env bash

set -e

status_ops="$*"

find . -name '.git' \
	| while read -r repo
do
	repo=${repo%".git"}
	(git -C "$repo" status -s \
		| grep -q -v "^\$" \
		&& echo -e "\n\033[1m${repo}\033[m" \
		&& git -C "$repo" status $status_ops) \
		|| true
done
