#!/usr/bin/env sh

if [ "$1" = "picom" ]; then
    pkill -x picom || picom -b --unredir-if-possible --backend xr_glx_hybrid --vsync --use-damage --glx-no-stencil
fi
if [ "$1" = "estado" ]; then
    herbstclient lock
    flutuante=$(herbstclient attr clients.focus.floating)
    telacheia=$(herbstclient attr clients.focus.fullscreen)
    if [ "$2" = "flutuante" ]; then
        [ "$telacheia" = "true" ] && herbstclient set_attr clients.focus.fullscreen false
        [ "$flutuante" = "false" ] && herbstclient set_attr clients.focus.floating true
        [ "$flutuante" = "true" ] && herbstclient set_attr clients.focus.floating false
    elif [ "$2" = "telacheia" ]; then
        [ "$flutuante" = "true" ] && herbstclient set_attr clients.focus.floating false
        [ "$telacheia" = "false" ] && herbstclient set_attr clients.focus.fullscreen true
        [ "$telacheia" = "true" ] && herbstclient set_attr clients.focus.fullscreen false
    fi
    herbstclient unlock
fi
