#!/usr/bin/env sh

preview() {
	cat <<-EOF | paste -sd '' >"$LF_FIFO_UEBERZUG"
	{
	"action": "add", "identifier": "lf-preview",
	"path": "$1", "x": $4, "y": $5, "width": $2, "height": $3,
	"scaler": "contain"
	}
	EOF
}

lf-cleaner # clean active preview

file="$1"; shift
case "$file" in
    *.tgz|*.tar.gz) tar tzf "$file";;
	*.tar.bz2|*.tbz2) tar tjf "$file";;
	*.tar.txz|*.txz) xz --list "$file";;
	*.tar) tar tf "$file";;
	*.[1-8]) man "$file" | col -b ;;
	*.o) nm "$file" | less ;;
    *.zip|*.jar|*.war|*.ear|*.oxt) unzip -l "$file" ;;
    *.rar) unrar l "$file" ;;
    *.7z) 7z l "$file" ;;
    *.avi|*.mp4|*.webm|*.mkv|*.wmv|*.dat|*.3gp|*.ogv|*.mkv|*.mpg|*.mpeg|*.vob|*.fl[icv]|*.m2v|*.mov|*.webm|*.ts|*.mts|*.m4v|*.r[am]|*.qt|*.divx)
        thumbnail="$LF_TEMPDIR/thumbnail.png"
        ffmpeg -y -i "$file" -vframes 1 "$thumbnail"
        preview "$thumbnail" "$@"
	;;
    *.pdf)
        thumbnail="$LF_TEMPDIR/thumbnail.png"
        gs -o "$thumbnail" -sDEVICE=pngalpha -dLastPage=1 "$file" >/dev/null
        preview "$thumbnail" "$@"
	;;
    *.jpg|*.jpeg|*.png|*.bmp)
        preview "$file" "$@"
    ;;
    *.svg)
        thumbnail="$LF_TEMPDIR/thumbnail.png"
        convert "$file" "$thumbnail"
        preview "$thumbnail" "$@"
	;;
    *.wav|*.mp3|*.flac|*.m4a|*.wma|*.ape|*.ac3|*.og[agx]|*.spx|*.opus|*.as[fx]|*.flac)
        exiftool "$file"
    ;;
    *.torrent)
        transmission-show "$file"
    ;;
    json)
        jq --color-output "$file"
    ;;
	*) highlight --out-format ansi "$file" || cat "$file" ;;
esac
return 127 # nonzero retcode required for lf previews to reload
