#!/usr/bin/env sh
DATE="$(date '+%d_%H:%M--%N')"
TRASH_FOLDER="${XDG_DATA_HOME:-$HOME/.local/share}/Trash"
CACHE_FOLDER="${XDG_CACHE_HOME:-$HOME/.cache}"
CACHE_FILE="$CACHE_FOLDER/lixo"

limpar() {
    TRASH_FOLDER_ESC="$(echo "$TRASH_FOLDER" | sed 's/\//\\\//g')"
    files="$(find "$TRASH_FOLDER" | sed "s/$TRASH_FOLDER_ESC\///g")"

    if [ "$files" = "$TRASH_FOLDER" ]; then
        echo "Nada na lixeira :)"
        exit 0
    else
        echo "$files"
        printf "Esvaziar a lixeira [Y/n]? "
        read -r answer

        if [ ! "$answer" != "${answer#[Nn]}" ]; then
            rm -r "$TRASH_FOLDER" "$CACHE_FILE"
            echo "Lixeira limpa!"
        fi

        exit 0
    fi
}

main() {
    [ ! -d "$TRASH_FOLDER" ] && mkdir "$TRASH_FOLDER"
    [ ! -d "$CACHE_FOLDER" ] && mkdir "$CACHE_FOLDER"

    if [ -z "$*" ]; then
        exit 1
    elif [ "$1" = "limpar" ]; then
        limpar "$@"
    else
        for arquivo in "$@"; do
            if [ -e "$arquivo" ]; then
                mv "$arquivo" "$TRASH_FOLDER/$arquivo--$DATE"
            else
                echo "Erro: $arquivo Não existe!"
                exit 1
            fi
        done

        if [ -e "$CACHE_FILE" ]; then
            quantia=$(cat "$CACHE_FILE")
            quantia=$((quantia + 1))
            echo $quantia >"$CACHE_FILE"
            if [ "$quantia" -gt 5 ]; then
                notify-send -u normal "Lixeira" "Limpe a sua lixeira!" ||
                    echo "Limpe a lixeira!"
            fi
        else
            touch "$CACHE_FILE"
            echo 1 >"$CACHE_FILE"
        fi
    fi
}

main "$@"
