#!/usr/bin/env sh
menu="dmenu -a -c -cw 500 -fn Monospace-18 -P -p"
[ "$XDG_SESSION_TYPE" = "wayland" ] && menu="fuzzel -d -I --terminal=term_open -x 0 -y 0 -p 0 -b 000000ff \
    -t ffffffff -m ff0000ff -S 000000ff -B 1 -r 0 -C ffffffff --show-actions -f Terminus:size=16 -P"

$menu "$1" <&- && echo
