#!/usr/bin/env sh

menu="tofi --anchor top --width 100% --padding-left 0 --prompt-text"
[ -z "$WAYLAND_DISPLAY" ] && menu="dmenu -l 15 -b -p"

pesquisa=$(printf "s
g
fb
yt
ytb
od
r
gh
gl
se
aw
aur
ew
fp
gt
br
tw
sc
al
alm
md
vn
imdb
vt
mj
dr
wu
gm
sf
gf
ud
tg
wm
editarmenu" | $menu "Pesquisar: ")

[ -z "$pesquisa" ] && exit # Sai com escape

procurado=${pesquisa#* }

case $pesquisa in
	aw) site="https://wiki.archlinux.org/" ;;
	al) site="https://anilist.co/user/Lucastavares/animelist" ;;
	alm) site="https://anilist.co/user/Lucastavares/mangalist" ;;
	aur) site="https://aur.archlinux.org" ;;
	br) site="https://brainly.com.br/" ;;
	dr) site="https://www.deltarune.com/" ;;
	fb) site="https://www.facebook.com/" ;;
	fp) site="https://www.freshports.org/" ;;
	g) site="https://www.google.com/" ;;
	gf) site="https://greasyfork.org/" ;;
	gh) site="https://github.com/" ;;
	gl) site="https://gitlab.com/" ;;
	gm) site="https://www.google.com.br/maps/" ;;
	gt) site="https://translate.google.com/" ;;
	imdb) site="https://www.imdb.com/" ;;
	ew) site="https://www.emacswiki.org" ;;
	md) site="https://mangadex.org/" ;;
	mj) site="https://tennhou.net/3/" ;;
	od) site="https://odysee.com/" ;;
	r) site="https://www.reddit.com/" ;;
	sc) site="https://soundcloud.com/you/likes" ;;
	se) site="https://stackexchange.com/" ;;
	sf) site="https://sourceforge.net/" ;;
	s) site="https://searx.be/" ;;
	tg) site="https://trends.google.com.br/" ;;
	tw) site="https://twitter.com/" ;;
	ud) site="https://www.urbandictionary.com/" ;;
	vn) site="https://vndb.org/" ;;
	vt) site="https://www.virustotal.com/gui/" ;;
	wa) site="https://web.whatsapp.com/" ;;
	wm) site="https://web.archive.org/" ;;
	yt) site="https://www.youtube.com/feed/subscriptions" ;;
	ytb) site="https://www.youtube.com/feed/library" ;;
	alm*)
		$BROWSER "https://anilist.co/search/manga?search=$procurado&sort=SEARCH_MATCH"
		;;
	al*)
		$BROWSER "https://anilist.co/search/anime?search=$procurado&sort=SEARCH_MATCH"
		;;
	aur*)
		$BROWSER "https://aur.archlinux.org/packages?O=0&SeB=nd&K=$procurado&outdated=&SB=p&SO=d&PP=50&submit=Go"
		;;
	aw*)
		$BROWSER "https://wiki.archlinux.org/index.php?search=$procurado"
		;;
	ew*)
		$BROWSER "https://html.duckduckgo.com/html?q=$procurado%20site%3Aemacswiki.org"
		;;
	br*)
		$BROWSER "https://brainly.com.br/app/ask?q=$procurado"
		;;
	fp*)
		$BROWSER "https://www.freshports.org/search.php?query=$procurado&search=go&num=10&stype=name&method=match&deleted=excludedeleted&start=1&casesensitivity=caseinsensitive"
		;;
	gf*)
		$BROWSER "https://greasyfork.org/en/scripts?q=$procurado"
		;;
	gh*)
		$BROWSER "https://github.com/search?q=$procurado"
		;;
	gl*)
		$BROWSER "https://gitlab.com/search?search=$procurado"
		;;
	gm*)
		$BROWSER "https://www.google.com.br/maps/search/$procurado"
		;;
	gt*)
		$BROWSER "https://translate.google.com/?sl=auto&tl=en&text=$procurado"
		;;
	g*)
		$BROWSER "https://www.google.com/search?q=$procurado"
		;;
	imdb*)
		$BROWSER "https://www.imdb.com/find?q=$procurado&ref_=nv_sr_sm"
		;;
	md*)
		$BROWSER "https://mangadex.org/titles?page=1&q=$procurado&order=relevance.desc"
		;;
	od*)
		$BROWSER "https://odysee.com/search?q=$procurado"
		;;
	r*)
		$BROWSER "https://www.reddit.com/search/?q=$procurado"
		;;
	sc*)
		$BROWSER "https://soundcloud.com/search?q=$procurado"
		;;
	se*)
		$BROWSER "https://stackexchange.com/search?q=$procurado"
		;;
	sf*)
		$BROWSER "https://sourceforge.net/directory/?q=$procurado"
		;;
	s*)
		$BROWSER "https://searx.be/search?q=$procurado"
		;;
	tw*)
		$BROWSER "https://twitter.com/search?q=$procurado"
		;;
	tg*)
		$BROWSER "https://trends.google.com.br/trends/explore?q=$procurado"
		;;
	ud*)
		$BROWSER "https://www.urbandictionary.com/define.php?term=$procurado"
		;;
	vn*)
		$BROWSER "https://vndb.org/v?sq=$procurado"
		;;
	wm*)
		$BROWSER "https://web.archive.org/web/*/$procurado"
		;;
	yt*)
		$BROWSER "https://www.youtube.com/results?search_query=$procurado"
		;;
	editarmenu) $VISUAL menu_pesquisar ;;
	*)
		$BROWSER
		;;
esac

[ -z "$site" ] && exit
$BROWSER --new-tab "$site"
