#!/usr/bin/env sh

# continua caso o mpd esteja aberto
if ! mpc > /dev/null ; then
    exit 0
fi

echo "$@" | grep -q prox && mpc next
echo "$@" | grep -q ante && mpc prev

# separa o nome da musica
caminho="$(mpc current -f %file%)" # /home/lucas/musica.mp3
arquivo=${caminho##*/} # musica.mp3
nome=${arquivo%.*} # musica
nome_curto=$(echo "$nome" | cut -c -40) # mus.. 40 caracteres

# posição na playlist
pos="$(mpc | grep -C 1 -o '[[:digit:]]*/[[:digit:]]* ')" # 10/25

echo "$@" | grep -q notificar && notify-send Tocando "$nome"
echo "$@" | grep -q tocando && printf "%s %s" "$nome_curto" "$pos"

exit 0
