#!/usr/bin/env sh

# continua caso o mpd esteja aberto
if ! mpc > /dev/null ; then
    exit 0
fi

# separa o nome da musica
caminho="$(mpc current -f %file%)" # /home/lucas/musica.mp3
arquivo=${caminho##*/} # musica.mp3
nome=${arquivo%.*} # musica
nome_curto=$(echo "$nome" | cut -c -40) # mus.. 40 caracteres

# faz alguma coisa
[ "$1" = "notificar" ] && notify-send Tocando "$nome"
[ "$1" = "tocando" ] && printf "%s" "$nome_curto"
