#!/bin/sh
if [ "$OS" = "archlinux" ]; then
    doas pacman -Sy >/dev/null 2>&1
    updates=$(paru -Qu 2> /dev/null | wc -l)
elif [ "$OS" = "linuxmint" ]; then
    doas apt update >/dev/null 2>&1
    updates=$(apt list --upgradable 2> /dev/null | wc -l)
fi

if [ "$updates" -gt 0 ]; then
    echo " $updates"
else
    echo ""
fi
