#!/usr/bin/env sh

if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
    menu="tofi"
    opcoes="Reiniciar\\nDesligar"
else
    menu="dmenu -a -l 3 -h 20 -c -cw 300"
    opcoes="Desligamento de tela\\nReiniciar\\nDesligar"
fi

if [ "$OS" = "artixlinux" ] || [ "$OS" = "voidlinux" ]; then
    reiniciar="doas reboot"
    desligar="doas poweroff"
elif [ "$OS" = "archlinux" ] || [ "$OS" = "manjaro" ]; then
    reiniciar="systemctl reboot"
    desligar="systemctl poweroff"
fi

case "$(printf "$opcoes" | $menu)" in
    "Desligamento de tela") dpms-toggle.sh ;;
    "Reiniciar") $reiniciar ;;
    "Desligar") $desligar ;;
esac
