#!/bin/sh

urlregex="(((http|https|gopher|gemini|ftp|ftps|git)://|www\\.)[a-zA-Z0-9.]*[:]?[a-zA-Z0-9./@$&%?$\#=_~-]*)|((magnet:\\?xt=urn:btih:)[a-zA-Z0-9]*)"

urls="$(sed 's/.*│//g' | tr -d '\n' |
	grep -aEo "$urlregex" |
	uniq |
	sed "s/\(\.\|,\|;\|\!\\|\?\)$//;
	s/^www./http:\/\/www\./")"

[ -z "$urls" ] && exit 1

while getopts "hoc" o; do case "${o}" in
	h) printf "Argumentos customizados:\\n  -c: copiar\\n  -o: xdg-open\\n  -h: Mostrar essa mensagem\\n" && exit 1 ;;
	o) chosen="$(echo "$urls" | dmenu -h 20 -p 'Abrir qual url?' -l 30)"
	setsid xdg-open "$chosen" >/dev/null 2>&1 & ;;
	c) echo "$urls" | dmenu -h 20 -p 'Copiar qual url?' -l 30 | tr -d '\n' | xclip -selection clipboard ;;
	*) printf "Opção invalida: -%s\\n" "$OPTARG" && exit 1 ;;
esac done
