#!/bin/sh

nvim_id=$(xdotool search --name "nvim")
dunst_id=$(xdotool search --class "dunst")
[ -z "$dunst_id" ] && [ -z "$nvim_id" ] && st_id=$(xdotool search --class "st")
[ -z "$dunst_id" ] && [ -n "$nvim_id" ] && st_id=$(xdotool search --class "st" | grep -v "$nvim_id")
[ -n "$dunst_id" ] && [ -z "$nvim_id" ] && st_id=$(xdotool search --class "st" | grep -v "$dunst_id")
[ -n "$dunst_id" ] && [ -n "$nvim_id" ] && st_id=$(xdotool search --class "st" | grep -v "$dunst_id" | grep -v "$nvim_id")

if [ -z "$st_id" ]; then
        st
else
    if [ ! -f /tmp/hide_scratch ]; then
            touch /tmp/hide_scratch && xdo hide $st_id
    elif [ -f /tmp/hide_scratch ]; then
            rm /tmp/hide_scratch && xdo show $st_id
    fi
fi
