#!/usr/bin/env sh

nvim_ids=$(xdotool search --name "nvim")
[ -z "$nvim_ids" ] && st_ids=$(xdotool search --class "st-256color")
[ -n "$nvim_ids" ] && st_ids=$(xdotool search --class "st-256color" | grep -v "$nvim_ids")

if [ -z "$st_ids" ]; then
    st
else
    if [ ! -f /tmp/hide_scratch ]; then
        touch /tmp/hide_scratch && xdo hide $st_ids
    elif [ -f /tmp/hide_scratch ]; then
        rm /tmp/hide_scratch && xdo show $st_ids
        [ "$WM" = "dwm" ] && dwmc inplacerotate +2
        [ "$WM" = "herbstluftwm" ] && herbstclient use 2
    fi
fi
