#!/bin/sh
st_id=$(xdotool search --class "st-256color")

if [ -z "$st_id" ]; then
    st
else
    if [ ! -f /tmp/hide_scratch ]; then
        touch /tmp/hide_scratch && xdo hide $st_id
    elif [ -f /tmp/hide_scratch ]; then
        rm /tmp/hide_scratch && xdo show $st_id
        [ "$WM" = "dwm" ] && dwmc inplacerotate +2
        [ "$WM" = "herbstluftwm" ] && herbstclient use 2
    fi
fi
