#!/usr/bin/env sh

vol="$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | sed 's/Volume: //;s/\.//;s/^0//;s/.* \[MUTED\]/0/')"

[ "$1" = "semicones" ] && printf "[%s%%]" "$vol" && exit 0

if [ "$vol" -gt "65" ]; then
	printf "%s %s%%" "🔊" "$vol"
elif [ "$vol" -gt "45" ]; then
	printf "%s %s%%" "🔉" "$vol"
elif [ "$vol" -gt "1" ]; then
	printf "%s %s%%" "🔈" "$vol"
elif [ "$vol" = "0" ]; then
	printf "🔇"
fi
