#!/usr/bin/env sh
print_nome="$HOME/print_$(date '+%d_%H:%M').png"
visualizar="nsxiv -t $print_nome"
menu="fuzzel -d -I --terminal=term_open -x 0 -y 0 -w 42 -p 0 -b 000000ff -t ffffffff -m ff0000ff -S 000000ff -B 1 -r 0 -C ffffffff --show-actions -f Terminus:size=16 -P"

case "$(printf "uma area selecionada\\numa janela\\ntela cheia (Temporizar)\\ntodas as telas (Temporizar)\\numa area selecionada (copiar)\
    \numa janela (copiar)\\ntela cheia (Temporizar) (copiar)\\ntodas as telas (Temporizar) (copiar)" | $menu "Area do print?")" in
    "uma area selecionada")
        grimshot --notify save area "$print_nome" && $visualizar ;;
    "uma janela")
        grimshot --notify save window "$print_nome" && $visualizar ;;
    "tela atual (Temporizar)")
        tempo=$(echo "" | $menu "Esperar em segundos:")
        sleep "$tempo" && grimshot --notify save output "$print_nome" && $visualizar ;;
    "todas as telas (Temporizar)")
        tempo=$(echo "" | $menu "Esperar em segundos:")
        sleep "$tempo" && grimshot --notify save screen "$print_nome" && $visualizar ;;
    "uma area selecionada (copiar)")
        grimshot --notify copy area ;;
    "uma janela (copiar)")
        grimshot --notify copy window ;;
    "tela atual (Temporizar) (copiar)")
        tempo=$(echo "" | $menu "Esperar em segundos:")
        sleep "$tempo" && grimshot --notify copy output ;;
    "todas as telas (Temporizar) (copiar)")
        tempo=$(echo "" | $menu "Esperar em segundos:")
        sleep "$tempo" && grimshot --notify copy screen ;;
esac
